apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      # From a trace span, navigate to Loki logs filtered by traceId
      tracesToLogs:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: false
        spanStartTimeShift: '-1m'
        spanEndTimeShift: '1m'
        customQuery: false
